const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pages=$$('.page');
function go(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));window.scrollTo(0,0);if(id==='status'){renderPrograms();}}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.go;if(['home','status','change'].includes(id))go(id);else showContent(id)}));

const content={
plan:['PLAN A PROGRAM','Start with scholar need, then design the program.',['Identify the scholar need or opportunity.','Define target scholars and realistic projected participation.','Define program model, provider, schedule, site, staffing and intended outcomes.','Use the current Extended Day application.']],
fund:['BUDGET & FUNDING','Identify the funding source before applying funding-specific rules.',['Confirm current allocation.','Identify 31a, 32n, 21st CCLC, Other, or Blended funding.','Build the proposed budget and calculate proposed cost per scholar.','Confirm allowability before committing funds.','Confirmed BOE threshold for this work: $30,321.']],
launch:['APPROVAL & LAUNCH','Approved and cleared to launch are not the same status.',['Confirm program decision.','Confirm final budget and funding.','Complete MOU/vendor requirements.','Complete BOE approval when applicable.','Do not launch while required approvals remain incomplete.']],
operate:['RUN MY PROGRAM','Manage the approved program without creating parallel processes.',['Track accurate attendance.','Use existing supply and inventory processes.','Use existing invoice/documentation procedures.','Follow closure/emergency procedures when needed.']],
evaluate:['MONITOR & EVALUATE','Use existing observation and evaluation tools.',['Review participation and delivery against what was approved.','Use the existing Observation Tool.','Assign action owner, due date and follow-up when improvement is needed.','Evaluate participation, implementation, quality, outcomes, investment, operations and partner performance.']],
vendor:['WORKING WITH A VENDOR','Use the existing vendor process from intake through closeout.',['Vendor intake/review.','Program and budget approval.','Insurance, staffing/background and other applicable requirements.','MOU/agreement.','Attendance, invoice and documentation expectations.','Evaluation and closeout.']],
resources:['FORMS & RESOURCES','Use authoritative GRPS tools rather than duplicate forms.',['2026–27 Submission Tracker','Current Extended Day application','School/quadrant allocation information','Vendor Intake / Third-Party Vendor Protocol','MOU / approval materials','Attendance resources','Supply ordering and inventory','Observation Tool','Vendor Evaluation Template','Extended Day Evaluation Plan','Closure / emergency SOP']],
faq:['FAQ','Key 2026–27 operating questions.',['Why is the process changing? — To strengthen planning, review, approval, monitoring and evaluation without adding unnecessary paperwork.','What is the BOE threshold? — $30,321 for this process.','Does application submission mean approval? — No.','Does approval mean a program can launch? — Not always; clearance requirements may remain.','Are all programs funded by 31a? — No. Funding may include 31a, 32n, 21st CCLC, other, or blended sources.','What if participation is low? — Identify, understand, adjust, monitor, and escalate persistent concerns.']]
};
function showContent(key){const d=content[key];$('#contentEyebrow').textContent=d[0];$('#contentTitle').textContent=d[0];$('#contentIntro').textContent=d[1];$('#contentBody').innerHTML='<div class="contentlist">'+d[2].map((x,i)=>`<div class="contentitem"><b>${i+1}.</b> ${x}</div>`).join('')+'</div>';go('content')}

function renderPrograms(q=''){const list=$('#programList');if(!list)return;const term=(q||$('#programSearch').value||'').toLowerCase();const rows=PROGRAMS.filter(p=>Object.values(p).join(' ').toLowerCase().includes(term));list.innerHTML=rows.length?rows.map((p,i)=>`<div class="programrow"><span>${p.school}</span><button data-prog="${PROGRAMS.indexOf(p)}">${p.program}</button><span>${p.provider}</span><span class="badge ${p.decision.startsWith('Approve')?'approve':'revise'}">${p.decision}</span></div>`).join(''):'<div class="result muted">No matching program found.</div>';$$('[data-prog]').forEach(b=>b.onclick=()=>showProgram(PROGRAMS[+b.dataset.prog]));}
function showProgram(p){$('#programDetail').innerHTML=`<div class="detail"><p class="eyebrow">PROGRAM DETAIL</p><h2>${p.program}</h2><p>${p.school} • ${p.provider}</p><div class="metrics"><div class="metric"><small>DECISION</small><b>${p.decision}</b></div><div class="metric"><small>OEL</small><b>${p.oel}</b></div><div class="metric"><small>MOU</small><b>${p.mou}</b></div><div class="metric"><small>REVIEW</small><b>${p.tier}</b></div><div class="metric"><small>START</small><b>${p.start}</b></div><div class="metric"><small>DURATION</small><b>${p.duration}</b></div></div><p><b>Schedule:</b> ${p.schedule}</p><p><b>Outcomes connection:</b> ${p.outcomes}</p><p><b>Threshold shown in source:</b> ${p.threshold}</p>${p.threshold.includes('31,320')?'<p class="revise"><b>Source correction needed:</b> this source label conflicts with the confirmed $30,321 BOE threshold.</p>':''}</div>`}
$('#programSearch').addEventListener('input',e=>renderPrograms(e.target.value));

SCHOOLS.forEach((s,i)=>$('#schoolSelect').insertAdjacentHTML('beforeend',`<option value="${i}">${s.school}</option>`));
$('#schoolSelect').addEventListener('change',e=>{const el=$('#schoolResult');if(e.target.value===''){el.className='result muted';el.textContent='Choose a school to see its budget and program decisions.';return}const s=SCHOOLS[+e.target.value];el.className='result';el.innerHTML=`<h2>${s.school}</h2><p>${s.principal}</p><div class="metrics"><div class="metric"><small>REQUESTED</small><b>${s.requested}</b></div><div class="metric"><small>AVAILABLE BUDGET</small><b>${s.budget}</b></div><div class="metric"><small>REMAINING</small><b>${s.remaining}</b></div></div>${s.items.map(x=>`<div class="programrow"><span>${x[0]}</span><span>${x[1]}</span><span class="badge ${x[2].toLowerCase()}">${x[2]}</span><span></span></div>`).join('')}<p><b>Revision due:</b> ${s.due}</p>`});

const changes={
'Budget':['FUNDING / MOU REVIEW','Check total cost, line items, funding source, vendor scope, MOU, and whether approval requirements change.'],
'Funding source':['FUNDING REVIEW','Do not switch funding sources informally. Route through OEL and applicable funding staff.'],
'Schedule':['OEL REVIEW','Meaningful schedule or dosage changes require review; minor operational adjustments may only need documentation.'],
'Location':['OEL REVIEW','Check site readiness, safety/licensing implications, agreement terms, and program approval.'],
'Staffing':['OEL REVIEW','Check budget, supervision, clearance, MOU, and funding implications.'],
'Vendor / partner':['ADDITIONAL REVIEW','A new provider may require intake, clearance, insurance, MOU, budget, and approval review.'],
'Program design':['OEL REVIEW','Determine whether the change materially alters the approved program or award requirements.'],
'Participation':['PROGRAM REVIEW','Compare projected and actual participation, identify barriers, adjust, monitor, and escalate persistent concerns.'],
'Program cannot operate today':['USE CLOSURE SOP','Follow the existing closure/emergency procedure and applicable notification, supervision, documentation, make-up, and billing rules.']
};
Object.entries(changes).forEach(([k,v])=>{const b=document.createElement('button');b.textContent=k;b.onclick=()=>{$('#changeResult').className='result';$('#changeResult').innerHTML=`<p class="eyebrow">${v[0]}</p><h2>${k}</h2><p>${v[1]}</p>`};$('#changeButtons').appendChild(b)});

$('#findBtn').onclick=()=>{const q=$('#homeSearch').value;go('status');$('#programSearch').value=q;renderPrograms(q);$('#programSearch').focus()};
$('#homeSearch').addEventListener('keydown',e=>{if(e.key==='Enter')$('#findBtn').click()});
renderPrograms();
